CREATE TABLE "personalInfo" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar DEFAULT 'John Carlo S. Misa' NOT NULL,
	"email" varchar DEFAULT 'johncarlomisa399@gmail.com' NOT NULL,
	"city" varchar DEFAULT 'San Pablo City' NOT NULL,
	"province" varchar DEFAULT 'Laguna' NOT NULL,
	"country" varchar DEFAULT 'Philippines' NOT NULL,
	"contactNumber" varchar NOT NULL,
	"industryRole" varchar NOT NULL,
	"profileImg" text,
	"coverImg" text,
	"itResumeLink" text NOT NULL,
	"vaResumeLink" text NOT NULL,
	"linkedinLink" text NOT NULL,
	"portfolioLink" text NOT NULL,
	"githubLink" text NOT NULL,
	"facebookLink" text NOT NULL,
	"instagramLink" text NOT NULL,
	"xLink" text NOT NULL,
	"about" text NOT NULL,
	"skills" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"topVoices" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"experiences" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"services" jsonb DEFAULT '[]'::jsonb NOT NULL
);
